### ISSUE TITLE
Intentional weight sharing in ResidualStack?

### ISSUE THREAD

**Issue by andreaskoepf** [zalandoresearch/pytorch-vq-vae#2]
The list passed to `nn.ModuleList` in the `ResidualStack` class ctor in [vae.ipynb#L324](https://github.com/zalandoresearch/pytorch-vq-vae/blob/9f30a64fde63c707ad69893fc546f8b716e02e62/vq-vae.ipynb#L324) duplicates a reference to a single `Residual` object instance. Was this done intentionally? 

```
self._layers = nn.ModuleList(
[Residual(in_channels, num_hiddens, num_residual_hiddens)] * self._num_residual_layers)
```

To create a new objects for each layer the code might be changed to:

```
self._layers = nn.ModuleList([Residual(in_channels, num_hiddens, num_residual_hiddens)
                             for _ in range(self._num_residual_layers)])
```

**Comment by kashif** [comment]
@andreaskoepf thanks for your observation... I think its a bug... I will fix it!
